In [1]:
! pip install gym

In [5]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [6]:
env= gym.make("FrozenLake-v0")

In [7]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table=np.zeros((state_space_size, action_space_size))
print(q_table)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Create Parameters to initialize and implement Q learning Algorithm

In [46]:
num_episodes=10000
max_steps_per_episode=500

learning_rate=0.1
discount_rate=0.99

exploration_rate=1
max_exploration_rate=1
min_exploration_rate=0.01
exploration_decay_rate=0.0001

Array to store the results of the Q-algorithm

In [47]:
rewards_all_episodes=[]

In [48]:
for episode in range(num_episodes):
  state=env.reset()

  done =False
  rewards_current_episode = 0

  for step in range (max_steps_per_episode):
    #exploration exploitation trade off

    exploration_rate_threshold=random.uniform(0,1)
    if exploration_rate_threshold> exploration_rate:
      action = np.argmax(q_table[state,:])
    else:
      action=env.action_space.sample()

    new_state,reward,done,info=env.step(action)
    #print (reward)

    # update the Q table for Q(s,a)
    q_table[state,action]=q_table[state,action]*(1-learning_rate) + learning_rate *(reward + discount_rate* np.max(q_table[new_state,:]))

    state=new_state
    rewards_current_episode += reward

    if done == True :
      break

  exploration_rate= min_exploration_rate + (max_exploration_rate-min_exploration_rate) * np.exp(-exploration_decay_rate* episode)

  rewards_all_episodes.append(rewards_current_episode)




In [49]:
np.shape(np.array(rewards_all_episodes))

(10000,)

Printing the training module for the game

In [50]:
rewards_per_thousdand_episodes=np.array_split(np.array(rewards_all_episodes),(num_episodes/1000))
count=1000
print("***************Q-Table***************\n")
for r in rewards_per_thousdand_episodes:
  print (count,":",str(sum(r/1000)))
  count +=1000

print("\n\n**********Q-Table********\n")
print(q_table)



***************Q-Table***************

1000 : 0.010000000000000002
2000 : 0.02100000000000001
3000 : 0.02900000000000002
4000 : 0.037000000000000026
5000 : 0.037000000000000026
6000 : 0.04500000000000003
7000 : 0.05300000000000004
8000 : 0.06700000000000005
9000 : 0.09000000000000007
10000 : 0.09700000000000007


**********Q-Table********

[[0.60022404 0.57601809 0.58849909 0.58259799]
 [0.29144816 0.39868003 0.35349108 0.54331817]
 [0.45451225 0.44493373 0.4249982  0.47967177]
 [0.29290399 0.32228461 0.21926915 0.45181137]
 [0.61813827 0.51014841 0.42197961 0.3990683 ]
 [0.         0.         0.         0.        ]
 [0.39515179 0.30546614 0.32206494 0.09037612]
 [0.         0.         0.         0.        ]
 [0.41320516 0.43318045 0.47774535 0.6375553 ]
 [0.6039905  0.69977735 0.39953161 0.51370907]
 [0.70496856 0.27000202 0.38448342 0.35221562]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.4995236  0.51218731 0.76838401 0.52023617]
