In [1]:
! pip install gym

In [2]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [3]:
env= gym.make("FrozenLake-v0")

In [4]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table=np.zeros((state_space_size, action_space_size))
print(q_table)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Create Parameters to initialize and implement Q learning Algorithm

In [19]:
num_episodes=10000
max_steps_per_episode=500

learning_rate=0.1
discount_rate=0.99

exploration_rate=1
max_exploration_rate=1
min_exploration_rate=0.01
exploration_decay_rate=0.01

Array to store the results of the Q-algorithm

In [20]:
rewards_all_episodes=[]

In [21]:
for episode in range(num_episodes):
  state=env.reset()

  done =False
  rewards_current_episode = 0

  for step in range (max_steps_per_episode):
    #exploration exploitation trade off

    exploration_rate_threshold=random.uniform(0,1)
    if exploration_rate_threshold> exploration_rate:
      action = np.argmax(q_table[state,:])
    else:
      action=env.action_space.sample()

    new_state,reward,done,info=env.step(action)
    #print (reward)

    # update the Q table for Q(s,a)
    q_table[state,action]=q_table[state,action]*(1-learning_rate) + learning_rate *(reward + discount_rate* np.max(q_table[new_state,:]))

    state=new_state
    rewards_current_episode += reward

    if done == True :
      break

  exploration_rate= min_exploration_rate + (max_exploration_rate-min_exploration_rate) * np.exp(-exploration_decay_rate* episode)

  rewards_all_episodes.append(rewards_current_episode)




In [22]:
np.shape(np.array(rewards_all_episodes))

(10000,)

Printing the training module for the game

In [23]:
rewards_per_thousdand_episodes=np.array_split(np.array(rewards_all_episodes),(num_episodes/1000))
count=1000
print("***************Q-Table***************\n")
for r in rewards_per_thousdand_episodes:
  print (count,":",str(sum(r/1000)))
  count +=1000

print("\n\n**********Q-Table********\n")
print(q_table)



***************Q-Table***************

1000 : 0.5230000000000004
2000 : 0.7020000000000005
3000 : 0.6660000000000005
4000 : 0.6640000000000005
5000 : 0.6810000000000005
6000 : 0.6960000000000005
7000 : 0.6940000000000005
8000 : 0.6610000000000005
9000 : 0.6690000000000005
10000 : 0.7040000000000005


**********Q-Table********

[[0.52809846 0.51334631 0.5021838  0.50838424]
 [0.27576817 0.35945406 0.3294851  0.48535794]
 [0.43418612 0.42058632 0.4146529  0.46265768]
 [0.24496471 0.31515621 0.17040509 0.45228573]
 [0.53784432 0.5215854  0.37057641 0.4055558 ]
 [0.         0.         0.         0.        ]
 [0.14376066 0.18210249 0.36721631 0.05949842]
 [0.         0.         0.         0.        ]
 [0.34604285 0.39173945 0.49472911 0.54702551]
 [0.41478116 0.60263285 0.44560138 0.37568563]
 [0.57370547 0.38417236 0.40557218 0.39259214]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.5163733  0.56906263 0.6911701  0.45250277]
 [0.72115523 

Testing the data

In [13]:
for episode in range(3):
  state =env.reset()
  done=False
  print("*****Episode ",episode+1,"*****\n\n\n")
  time.sleep(1)

  for step in range(max_steps_per_episode):
    clear_output(wait=True)
    env.render()
    time.sleep(0.3)

    action =np.argmax(q_table[state,:])
    new_state,reward,done,info=env.step(action)

    if done:
        clear_output(wait=True)
        env.render()
        if reward==1:
          print("****you reached the goal*****")
          time.sleep(3)
        else:
          print("****you fell in hole*****")
          time.sleep(3)

        clear_output(wait=True)
        break

    state=new_state

env.close()
        

      



  

  (Left)
SFFF
FHFH
FFFH
HFFG
****you fell in hole*****
